### PR TITLE
fix Dict deprecation warnings closes #23

### LINKED ISSUE #23: Deprecation warnings
````julia
WARNING: deprecated syntax "{a=>b, ...}" at /Users/Administrator/.julia/v0.4/GnuTLS/src/errormap.jl:155.
Use "Dict{Any,Any}(a=>b, ...)" instead.
````

https://github.com/milktrader/Quandl.jl/issues/61

### PR DESCRIPTION
**Pull request by milktrader**

### CODE REVIEW

**Comment by sbromberger** [comment]
@milktrader - I just (inadvertently) submitted a similar PR. What do you mean that yours was premature?

**Comment by milktrader** [comment]
The warnings only apply to `v0.4` and removing them would involve syntax change that doesn't apply to `v0.3`,  thereby break the package on `v0.3`, which is the current stable release. 

Does your PR have a control flow like this?
````julia
RawBlameHistory   
if VERSION < v"0.4-"
    # use new syntax
else
    # use old syntax
end
````
The `Compat` package is designed to take of this but I haven't actually used the package yet.

**Comment by sbromberger** [comment]
I did it using Compat and using `@compat` before `Dict`. This works in 0.3 and 0.4.

**Comment by milktrader** [comment]
Cool!

I need to learn this. Can you point me to your code?

**Comment by sbromberger** [comment]
I take it back :) @compat broke 0.4. It's fixed now. Check out my PR for details: https://github.com/JuliaWeb/GnuTLS.jl/pull/28/files .

**Pull request closed without merging**
