### PR TITLE
Add new apt-get and yum packages

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by nalimilan** [comment]
While you're at it, can you add https://github.com/JuliaWeb/GnuTLS.jl/pull/42 to this PR? I'd be more careful than that PR, and keep `libgnutls` just in case it's actually correct on some distro.

**Comment by staticfloat** [comment]
Done.

**Comment by nalimilan** [comment]
Thanks!

**Comment by binarybana** [comment]
I must be getting old... because I've now supplied two separate PRs for this issue without realizing it!

Can we get this merged pretty please? :ice_cream: 

If anyone wants to test these kinds of things in the future, feel free to use my Dockerfile here: https://github.com/JuliaWeb/HttpParser.jl/issues/32#issuecomment-118240269

**Comment by tmlbl** [comment]
+1 for the Debian update

**Comment by staticfloat** [comment]
@quinnj @amitmurthy @Keno could one of you merge this for us?

**Pull request merged**
